-- DentAIstudy: chat history tables (max 10 conversations per user)
-- Run in Supabase Dashboard → SQL Editor
-- Safe to run multiple times (idempotent-ish).

create extension if not exists "pgcrypto";

-- =========================
-- Tables + Indexes
-- =========================
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists conversations_user_updated_idx
  on public.conversations (user_id, updated_at desc, created_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_created_idx
  on public.messages (conversation_id, created_at asc);

-- =========================
-- Triggers: updated_at touch
-- =========================
create or replace function public.touch_conversation_updated_at()
returns trigger
language plpgsql
as $$
begin
  update public.conversations
  set updated_at = now()
  where id = new.conversation_id;

  return new;
end;
$$;

drop trigger if exists messages_touch_conversation on public.messages;
create trigger messages_touch_conversation
after insert on public.messages
for each row execute function public.touch_conversation_updated_at();

-- =========================
-- Enforce max 10 conversations per user (SPAM-SAFE)
-- =========================
create or replace function public.prune_conversations_to_10()
returns trigger
language plpgsql
as $$
begin
  -- Serialize per-user within the transaction to avoid race conditions under spam clicks
  perform pg_advisory_xact_lock(hashtext(new.user_id::text));

  delete from public.conversations c
  where c.user_id = new.user_id
    and c.id in (
      select id
      from public.conversations
      where user_id = new.user_id
      order by updated_at desc, created_at desc, id desc
      offset 10
    );

  return new;
end;
$$;

drop trigger if exists conversations_prune on public.conversations;
create trigger conversations_prune
after insert on public.conversations
for each row execute function public.prune_conversations_to_10();

-- =========================
-- RLS
-- =========================
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Conversations policy
drop policy if exists "Users can CRUD their conversations" on public.conversations;
create policy "Users can CRUD their conversations"
on public.conversations
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Messages policies
drop policy if exists "Users can read messages in their conversations" on public.messages;
create policy "Users can read messages in their conversations"
on public.messages
for select
using (
  exists (
    select 1
    from public.conversations c
    where c.id = messages.conversation_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists "Users can insert messages in their conversations" on public.messages;
create policy "Users can insert messages in their conversations"
on public.messages
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.conversations c
    where c.id = messages.conversation_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists "Users can update messages in their conversations" on public.messages;
create policy "Users can update messages in their conversations"
on public.messages
for update
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.conversations c
    where c.id = messages.conversation_id
      and c.user_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.conversations c
    where c.id = messages.conversation_id
      and c.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete messages in their conversations" on public.messages;
create policy "Users can delete messages in their conversations"
on public.messages
for delete
using (
  auth.uid() = user_id
  and exists (
    select 1
    from public.conversations c
    where c.id = messages.conversation_id
      and c.user_id = auth.uid()
  )
);
